keywords:
    positive:
        - affordance
        - imagin
        - encode
        - robot
        - embodied
        - agent
        - task
        - egocentric
        - emergent
        - ecological
        - ecology
        - self-supervised
        - percept
        - unsupervised
        - visual cortex
    negative:
        - large language model
        - language model
        - llm
        - supervised
        - label
        - discretize
    neutral:
        - visual
        - predict
        - centric
        - learn
        - transformer
        - unseen
        - embedding
        - latent
        - multimodal
        - behavior
        - mice
        - mouse
        - animal
        - biolog
        - primate
references: {}
    
discoveryAttempts: []