#!/usr/bin/env -S deno run --allow-all --no-lock
import { FileSystem, glob } from "https://deno.land/x/quickr@0.8.0/main/file_system.js"

const concepts = {
    "spike-based": ["spike based", "spiking", "snn"],
    "neuromorphic": ["memristive","loihi"],
    "event-based camera": ["event based camera", "neuromorphic camera", "event camera "],
    "neurorobotic": ["neuro-robotic", "neuro robotic", ],
    "localization": ["localisation"],
    "neurophysiological": ["neurophysiological"],
    "hierarchical temporal memory": [],
    "stereo": ["stereoscopic"],
    "place recognition":[],
    "place cells": [],
    "grid cells": [],
    "stripe cells": [],
    "border cells": [],
    "boundary vector cells": ["BVC"],
    "head direction cells": ["HDC"],
    "pose cells": [],
    "view cells": [],
    "multidimensional continuous attractor": ["MD-CAN", "MD-CANN"],
    "continuous attractor nerual network": ["CANN"],
    "continuous attractor network": ["CAN"],
    "continuous attractor": [],
    "ring attractor": [],
    "path integration": [],
    "entorhinal": ["MEC"],
    "experience map": [],
    "3d experience map": [],
    "pose estimation": [],
    "sparse distributed representation": ["SDR"],
    "hebbian": [],
    "plasticity": [],
    "hippocampus": ["hippocampal",],
    "landmark":[],
    "landmark stability": [],
    "robot": ["robotics",],
    "temporal": [],
    "task": [],
    "optical flow": [],
    "ecological": ["ecology",],
    "low-energy": [],
    "ugv": ["unmanned ground vehicle", "legged", "quadruped",],
    "uav": ["unmanned aerial vehicle"],
    "attention": [],
    "learning": ["learn", "learned"],
    "spatial": [],
    "navigation": [],
    "ratslam": [],
    "Kalman Filters": [],
}
for (const [key, value] of Object.entries(concepts)) {
    value.push(key)
    var i=-1
    for (var each of value) {
        i++
        value[i] = each.toLowerCase()
    }
}

import { pathPieces } from 'https://esm.sh/gh/jeff-hykin/good-js@1.17.0.0/source/flattened/path_pieces.js'
import { escapeRegexMatch } from 'https://esm.sh/gh/jeff-hykin/good-js@1.17.0.0/source/flattened/escape_regex_match.js'
import { shallowSortObject } from 'https://esm.sh/gh/jeff-hykin/good-js@1.17.0.0/source/flattened/shallow_sort_object.js'
let frequencyMapOf = {}
for (let each of await glob(`${FileSystem.thisFolder}/../pdfs/qualified_systems/*.txt`)) {
    let [folders, name, ext] = pathPieces(each)
    console.debug(`name is:`,name)
    let bodyText = await FileSystem.read(each)
    bodyText = bodyText.toLowerCase().replace(/\s+/g," ")
    console.debug(`bodyText is:`,bodyText.length)
    console.debug(`bodyText is:`,bodyText.slice(0,1000).replace(/\s+/g," "))
    frequencyMapOf[name] = {}
    for (const [key, value] of Object.entries(concepts)) {
        const pattern = new RegExp(`\\b(${value.map(escapeRegexMatch).join("|")})\\b`, "g")
        let count = (bodyText.match(pattern)||[]).length
        frequencyMapOf[name][key] = count
    }
    frequencyMapOf[name] = Object.fromEntries([...Object.entries(frequencyMapOf[name])].sort((a,b)=>b[1]-a[1]))
}

console.log(JSON.stringify(frequencyMapOf, null, 4))


// {
//     "2018_HippoSLAM": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2024_SbcSLAM": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2024_WaterSLAM2": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2004_RatSLAM": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2023_NeuroGPR": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2020_NeuroSLAM2": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2024_SurfSLAM": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2022_NeoSLAM1": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2017_RodentSLAM": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2013_WaterSLAM1": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2019_BionicSLAM": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2024_NeoSLAM2": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2017_CogSLAM": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     },
//     "2019_NeuroSLAM1": {
//         "robot": 43,
//         "ratslam": 27,
//         "hippocampus": 13,
//         "continuous attractor network": 12,
//         "landmark": 12,
//         "localization": 11,
//         "path integration": 10,
//         "pose cells": 9,
//         "learning": 6,
//         "navigation": 4,
//         "view cells": 3,
//         "spatial": 2,
//         "place cells": 1,
//         "pose estimation": 1,
//         "hebbian": 1,
//         "spike-based": 0,
//         "neuromorphic": 0,
//         "event-based camera": 0,
//         "neurorobotic": 0,
//         "neurophysiological": 0,
//         "hierarchical temporal memory": 0,
//         "stereo": 0,
//         "place recognition": 0,
//         "grid cells": 0,
//         "stripe cells": 0,
//         "border cells": 0,
//         "boundary vector cells": 0,
//         "head direction cells": 0,
//         "multidimensional continuous attractor": 0,
//         "continuous attractor nerual network": 0,
//         "continuous attractor": 0,
//         "ring attractor": 0,
//         "entorhinal": 0,
//         "experience map": 0,
//         "3d experience map": 0,
//         "sparse distributed representation": 0,
//         "plasticity": 0,
//         "landmark stability": 0,
//         "temporal": 0,
//         "task": 0,
//         "optical flow": 0,
//         "ecological": 0,
//         "low-energy": 0,
//         "ugv": 0,
//         "uav": 0,
//         "attention": 0,
//         "Kalman Filters": 0
//     }
// }