#!/usr/bin/env -S deno run --allow-all --no-lock
import { FileSystem, glob } from "https://deno.land/x/quickr@0.8.0/main/file_system.js"

const concepts = {
    "spike-based": ["spike based", "spiking", "snn", "spiking neural network", "spiking neural networks"],
    "neuromorphic": ["memristive","loihi"],
    "event-based camera": ["event based camera", "neuromorphic camera", "event camera "],
    "neurorobotic": ["neuro-robotic", "neuro robotic", ],
    "localization": ["localisation"],
    "neurophysiological": ["neurophysiological"],
    "hierarchical temporal memory": [],
    "stereo": ["stereoscopic"],
    "place recognition":[],
    "place cells": [],
    "grid cells": [],
    "stripe cells": [],
    "border cells": [],
    "boundary vector cells": ["BVC"],
    "head direction cells": ["HDC"],
    "pose cells": [],
    "object vector cells": [],
    "view cells": [],
    "multidimensional continuous attractor": ["MD-CAN", "MD-CANN"],
    "continuous attractor nerual network": ["CANN"],
    "continuous attractor network": [],
    "continuous attractor": [ "CANN", "MD-CAN", "MD-CANN"],
    "ring attractor": [],
    "path integration": [],
    "entorhinal": ["MEC"],
    "experience map": [],
    "3d experience map": [],
    "pose estimation": [],
    "sparse distributed representation": ["SDR"],
    "hebbian": [],
    "plasticity": [],
    "hippocampus": ["hippocampal",],
    "landmark":[],
    "landmark stability": [],
    "robot": ["robotics",],
    "temporal": [],
    "task": [],
    "optical flow": [],
    "ecological": ["ecology",],
    "low-energy": [],
    "ugv": ["unmanned ground vehicle", "legged", "quadruped",],
    "uav": ["unmanned aerial vehicle"],
    "attention": [],
    "learning": ["learn", "learned"],
    "spatial": [],
    "navigation": [],
    "ratslam": [],
    "Kalman Filters": [],
    "RatNav": ["RatNav1", "RatNav2",],
    "NeuroSLAM": [],
    "NeoSLAM": [],
    "Underwater": ["water"],
}
for (const [key, value] of Object.entries(concepts)) {
    value.push(key)
    var i=-1
    for (var each of value) {
        i++
        value[i] = each.toLowerCase()
    }
}

import { pathPieces } from 'https://esm.sh/gh/jeff-hykin/good-js@1.17.0.0/source/flattened/path_pieces.js'
import { escapeRegexMatch } from 'https://esm.sh/gh/jeff-hykin/good-js@1.17.0.0/source/flattened/escape_regex_match.js'
import { shallowSortObject } from 'https://esm.sh/gh/jeff-hykin/good-js@1.17.0.0/source/flattened/shallow_sort_object.js'
let frequencyMapOf = {}
for (let each of await glob(`${FileSystem.thisFolder}/../pdfs/qualified_systems/*.txt`)) {
    let [folders, name, ext] = pathPieces(each)
    let bodyText = await FileSystem.read(each)
    bodyText = bodyText.toLowerCase().replace(/\s+/g," ")
    frequencyMapOf[name] = {}
    for (const [key, value] of Object.entries(concepts)) {
        const pattern = new RegExp(`\\b(${value.map(escapeRegexMatch).join("|")})\\b`, "g")
        let count = (bodyText.match(pattern)||[]).length
        frequencyMapOf[name][key] = count
    }
    frequencyMapOf[name] = Object.fromEntries([...Object.entries(frequencyMapOf[name])].sort((a,b)=>b[1]-a[1]))
}
for (let each of await glob(`${FileSystem.thisFolder}/../pdfs/nicknamed/*.txt`)) {
    let [folders, name, ext] = pathPieces(each)
    let bodyText = await FileSystem.read(each)
    bodyText = bodyText.toLowerCase().replace(/\s+/g," ")
    frequencyMapOf[name] = {}
    for (const [key, value] of Object.entries(concepts)) {
        const pattern = new RegExp(`\\b(${value.map(escapeRegexMatch).join("|")})\\b`, "g")
        let count = (bodyText.match(pattern)||[]).length
        frequencyMapOf[name][key] = count
    }
    frequencyMapOf[name] = Object.fromEntries([...Object.entries(frequencyMapOf[name])].sort((a,b)=>b[1]-a[1]))
}

console.log(JSON.stringify(frequencyMapOf, null, 4))

var output = {
    "2018_HippoSLAM": {
        "spatial": 68,
        "localization": 61,
        "robot": 49,
        "grid cells": 43,
        "hippocampus": 32,
        "place cells": 31,
        "navigation": 29,
        "learning": 28,
        "entorhinal": 22,
        "head direction cells": 17,
        "path integration": 14,
        "neurophysiological": 4,
        "landmark": 3,
        "view cells": 2,
        "continuous attractor network": 2,
        "continuous attractor": 2,
        "hebbian": 2,
        "place recognition": 1,
        "ecological": 1,
        "spike-based": 0,
        "neuromorphic": 0,
        "event-based camera": 0,
        "neurorobotic": 0,
        "hierarchical temporal memory": 0,
        "stereo": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "pose cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "ring attractor": 0,
        "experience map": 0,
        "3d experience map": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "plasticity": 0,
        "landmark stability": 0,
        "temporal": 0,
        "task": 0,
        "optical flow": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "attention": 0,
        "ratslam": 0,
        "Kalman Filters": 0
    },
    "2024_SbcSLAM": {
        "robot": 37,
        "spatial": 24,
        "localization": 16,
        "navigation": 13,
        "head direction cells": 12,
        "grid cells": 10,
        "uav": 9,
        "experience map": 8,
        "stereo": 7,
        "hippocampus": 6,
        "ugv": 6,
        "learning": 6,
        "path integration": 4,
        "place cells": 3,
        "entorhinal": 2,
        "temporal": 2,
        "continuous attractor network": 1,
        "continuous attractor": 1,
        "hebbian": 1,
        "ratslam": 1,
        "spike-based": 0,
        "neuromorphic": 0,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "place recognition": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "pose cells": 0,
        "view cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "ring attractor": 0,
        "3d experience map": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "plasticity": 0,
        "landmark": 0,
        "landmark stability": 0,
        "task": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "attention": 0,
        "Kalman Filters": 0
    },
    "2024_WaterSLAM2": {
        "localization": 16,
        "robot": 16,
        "spike-based": 14,
        "spatial": 10,
        "neuromorphic": 7,
        "learning": 6,
        "navigation": 6,
        "pose cells": 5,
        "experience map": 4,
        "view cells": 2,
        "continuous attractor": 2,
        "path integration": 2,
        "plasticity": 2,
        "temporal": 2,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "stereo": 0,
        "place recognition": 0,
        "place cells": 0,
        "grid cells": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "head direction cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "continuous attractor network": 0,
        "ring attractor": 0,
        "entorhinal": 0,
        "3d experience map": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "hebbian": 0,
        "hippocampus": 0,
        "landmark": 0,
        "landmark stability": 0,
        "task": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "attention": 0,
        "ratslam": 0,
        "Kalman Filters": 0
    },
    "2004_RatSLAM": {
        "robot": 43,
        "ratslam": 25,
        "pose cells": 16,
        "path integration": 13,
        "hippocampus": 13,
        "localization": 12,
        "landmark": 12,
        "learning": 6,
        "view cells": 4,
        "navigation": 4,
        "spatial": 2,
        "place cells": 1,
        "head direction cells": 1,
        "pose estimation": 1,
        "hebbian": 1,
        "spike-based": 0,
        "neuromorphic": 0,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "stereo": 0,
        "place recognition": 0,
        "grid cells": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "continuous attractor network": 0,
        "continuous attractor": 0,
        "ring attractor": 0,
        "entorhinal": 0,
        "experience map": 0,
        "3d experience map": 0,
        "sparse distributed representation": 0,
        "plasticity": 0,
        "landmark stability": 0,
        "temporal": 0,
        "task": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "attention": 0,
        "Kalman Filters": 0
    },
    "2023_NeuroGPR": {
        "robot": 72,
        "place recognition": 39,
        "neuromorphic": 33,
        "spike-based": 26,
        "continuous attractor": 21,
        "continuous attractor nerual network": 18,
        "spatial": 17,
        "navigation": 9,
        "view cells": 8,
        "learning": 8,
        "temporal": 7,
        "head direction cells": 6,
        "hippocampus": 6,
        "place cells": 5,
        "entorhinal": 5,
        "task": 5,
        "ugv": 5,
        "plasticity": 2,
        "event-based camera": 1,
        "localization": 1,
        "stereo": 1,
        "grid cells": 1,
        "pose estimation": 1,
        "attention": 1,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "pose cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor network": 0,
        "ring attractor": 0,
        "path integration": 0,
        "experience map": 0,
        "3d experience map": 0,
        "sparse distributed representation": 0,
        "hebbian": 0,
        "landmark": 0,
        "landmark stability": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "uav": 0,
        "ratslam": 0,
        "Kalman Filters": 0
    },
    "2020_NeuroSLAM2": {
        "robot": 33,
        "place cells": 26,
        "spike-based": 18,
        "path integration": 15,
        "ratslam": 15,
        "localization": 13,
        "head direction cells": 12,
        "experience map": 9,
        "spatial": 8,
        "navigation": 8,
        "hippocampus": 6,
        "continuous attractor": 4,
        "learning": 3,
        "stereo": 2,
        "neuromorphic": 1,
        "continuous attractor network": 1,
        "pose estimation": 1,
        "ugv": 1,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "place recognition": 0,
        "grid cells": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "pose cells": 0,
        "view cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "ring attractor": 0,
        "entorhinal": 0,
        "3d experience map": 0,
        "sparse distributed representation": 0,
        "hebbian": 0,
        "plasticity": 0,
        "landmark": 0,
        "landmark stability": 0,
        "temporal": 0,
        "task": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "uav": 0,
        "attention": 0,
        "Kalman Filters": 0
    },
    "2024_SurfSLAM": {
        "ratslam": 95,
        "experience map": 26,
        "robot": 20,
        "view cells": 10,
        "attention": 8,
        "navigation": 8,
        "localization": 6,
        "hippocampus": 5,
        "spatial": 5,
        "place cells": 4,
        "grid cells": 4,
        "pose cells": 4,
        "spike-based": 3,
        "head direction cells": 2,
        "path integration": 2,
        "entorhinal": 2,
        "neuromorphic": 1,
        "pose estimation": 1,
        "temporal": 1,
        "task": 1,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "stereo": 0,
        "place recognition": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "continuous attractor network": 0,
        "continuous attractor": 0,
        "ring attractor": 0,
        "3d experience map": 0,
        "sparse distributed representation": 0,
        "hebbian": 0,
        "plasticity": 0,
        "landmark": 0,
        "landmark stability": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "learning": 0,
        "Kalman Filters": 0
    },
    "2022_NeoSLAM1": {
        "robot": 32,
        "navigation": 23,
        "experience map": 17,
        "learning": 14,
        "grid cells": 12,
        "head direction cells": 10,
        "hebbian": 6,
        "place recognition": 4,
        "place cells": 4,
        "entorhinal": 4,
        "stereo": 3,
        "continuous attractor": 3,
        "path integration": 3,
        "landmark": 3,
        "spatial": 3,
        "localization": 2,
        "continuous attractor network": 2,
        "ratslam": 2,
        "3d experience map": 1,
        "spike-based": 0,
        "neuromorphic": 0,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "pose cells": 0,
        "view cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "ring attractor": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "plasticity": 0,
        "hippocampus": 0,
        "landmark stability": 0,
        "temporal": 0,
        "task": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "attention": 0,
        "Kalman Filters": 0
    },
    "2017_AdaptSLAM": {
        "navigation": 75,
        "robot": 55,
        "hippocampus": 31,
        "spatial": 30,
        "entorhinal": 17,
        "learning": 15,
        "grid cells": 14,
        "localization": 10,
        "place cells": 10,
        "path integration": 9,
        "spike-based": 8,
        "landmark": 7,
        "task": 7,
        "neurophysiological": 4,
        "boundary vector cells": 4,
        "continuous attractor network": 4,
        "continuous attractor": 4,
        "neuromorphic": 3,
        "head direction cells": 3,
        "place recognition": 2,
        "stereo": 1,
        "event-based camera": 0,
        "neurorobotic": 0,
        "hierarchical temporal memory": 0,
        "stripe cells": 0,
        "border cells": 0,
        "pose cells": 0,
        "view cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "ring attractor": 0,
        "experience map": 0,
        "3d experience map": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "hebbian": 0,
        "plasticity": 0,
        "landmark stability": 0,
        "temporal": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "attention": 0,
        "ratslam": 0,
        "Kalman Filters": 0
    },
    "2013_WaterSLAM1": {
        "robot": 30,
        "continuous attractor": 15,
        "ratslam": 15,
        "spatial": 14,
        "pose cells": 13,
        "hippocampus": 13,
        "path integration": 12,
        "grid cells": 10,
        "localization": 9,
        "place cells": 9,
        "view cells": 8,
        "head direction cells": 7,
        "navigation": 7,
        "continuous attractor nerual network": 5,
        "experience map": 5,
        "learning": 5,
        "continuous attractor network": 1,
        "entorhinal": 1,
        "task": 1,
        "Kalman Filters": 1,
        "spike-based": 0,
        "neuromorphic": 0,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "stereo": 0,
        "place recognition": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "multidimensional continuous attractor": 0,
        "ring attractor": 0,
        "3d experience map": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "hebbian": 0,
        "plasticity": 0,
        "landmark": 0,
        "landmark stability": 0,
        "temporal": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "attention": 0
    },
    "2019_BionicSLAM": {
        "navigation": 68,
        "grid cells": 63,
        "place cells": 51,
        "robot": 50,
        "hippocampus": 32,
        "stripe cells": 31,
        "spatial": 31,
        "head direction cells": 20,
        "entorhinal": 16,
        "path integration": 14,
        "learning": 14,
        "continuous attractor": 6,
        "ratslam": 5,
        "localization": 4,
        "ring attractor": 4,
        "spike-based": 2,
        "landmark": 2,
        "hebbian": 1,
        "landmark stability": 1,
        "temporal": 1,
        "neuromorphic": 0,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "hierarchical temporal memory": 0,
        "stereo": 0,
        "place recognition": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "pose cells": 0,
        "view cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "continuous attractor network": 0,
        "experience map": 0,
        "3d experience map": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "plasticity": 0,
        "task": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "attention": 0,
        "Kalman Filters": 0
    },
    "2024_NeoSLAM2": {
        "robot": 69,
        "spatial": 41,
        "ratslam": 33,
        "learning": 28,
        "temporal": 24,
        "view cells": 22,
        "place recognition": 21,
        "hippocampus": 15,
        "sparse distributed representation": 10,
        "localization": 9,
        "hierarchical temporal memory": 9,
        "entorhinal": 9,
        "pose cells": 7,
        "experience map": 7,
        "grid cells": 4,
        "continuous attractor": 4,
        "navigation": 4,
        "hebbian": 3,
        "plasticity": 3,
        "task": 3,
        "ugv": 3,
        "place cells": 2,
        "continuous attractor nerual network": 2,
        "spike-based": 1,
        "stereo": 1,
        "border cells": 1,
        "continuous attractor network": 1,
        "landmark": 1,
        "neuromorphic": 0,
        "event-based camera": 0,
        "neurorobotic": 0,
        "neurophysiological": 0,
        "stripe cells": 0,
        "boundary vector cells": 0,
        "head direction cells": 0,
        "multidimensional continuous attractor": 0,
        "ring attractor": 0,
        "path integration": 0,
        "3d experience map": 0,
        "pose estimation": 0,
        "landmark stability": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "uav": 0,
        "attention": 0,
        "Kalman Filters": 0
    },
    "2017_EpisodicSLAM": {
        "robot": 107,
        "task": 64,
        "navigation": 47,
        "hippocampus": 35,
        "spatial": 25,
        "localization": 23,
        "experience map": 19,
        "learning": 19,
        "entorhinal": 13,
        "spike-based": 8,
        "ratslam": 8,
        "continuous attractor": 7,
        "temporal": 6,
        "place cells": 4,
        "continuous attractor network": 4,
        "neuromorphic": 3,
        "grid cells": 3,
        "path integration": 3,
        "neurophysiological": 2,
        "stereo": 2,
        "place recognition": 1,
        "pose cells": 1,
        "view cells": 1,
        "attention": 1,
        "event-based camera": 0,
        "neurorobotic": 0,
        "hierarchical temporal memory": 0,
        "stripe cells": 0,
        "border cells": 0,
        "boundary vector cells": 0,
        "head direction cells": 0,
        "multidimensional continuous attractor": 0,
        "continuous attractor nerual network": 0,
        "ring attractor": 0,
        "3d experience map": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "hebbian": 0,
        "plasticity": 0,
        "landmark": 0,
        "landmark stability": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "ugv": 0,
        "uav": 0,
        "Kalman Filters": 0
    },
    "2019_NeuroSLAM1": {
        "robot": 111,
        "head direction cells": 82,
        "spatial": 63,
        "grid cells": 62,
        "experience map": 44,
        "continuous attractor": 40,
        "navigation": 28,
        "multidimensional continuous attractor": 26,
        "path integration": 25,
        "learning": 24,
        "localization": 20,
        "view cells": 17,
        "place cells": 14,
        "ratslam": 14,
        "pose cells": 13,
        "spike-based": 10,
        "hippocampus": 10,
        "continuous attractor nerual network": 9,
        "stereo": 8,
        "place recognition": 8,
        "neuromorphic": 6,
        "entorhinal": 5,
        "landmark": 4,
        "Kalman Filters": 4,
        "3d experience map": 3,
        "event-based camera": 2,
        "continuous attractor network": 2,
        "hebbian": 2,
        "neurophysiological": 1,
        "border cells": 1,
        "plasticity": 1,
        "task": 1,
        "ugv": 1,
        "neurorobotic": 0,
        "hierarchical temporal memory": 0,
        "stripe cells": 0,
        "boundary vector cells": 0,
        "ring attractor": 0,
        "pose estimation": 0,
        "sparse distributed representation": 0,
        "landmark stability": 0,
        "temporal": 0,
        "optical flow": 0,
        "ecological": 0,
        "low-energy": 0,
        "uav": 0,
        "attention": 0
    }
}
let totalFreq = {}
for (const [whichPaper, value] of Object.entries(frequencyMapOf)) {
    for (const [whichTerm, count] of Object.entries(value)) {
        totalFreq[whichTerm] = (totalFreq[whichTerm] || 0) + count
    }
}
// sort
totalFreq = Object.fromEntries([...Object.entries(totalFreq)].sort((a,b)=>b[1]-a[1]))
const conceptNames = Object.keys(totalFreq)
let csvOutput=[]
const columnNames = conceptNames
csvOutput.push(["Name","Year", ...columnNames])
const keys = Object.keys(frequencyMapOf).sort()
for (const key of keys) {
    const value = frequencyMapOf[key]
    const [name, year] = key.split("_").reverse()
    csvOutput.push([name, year||"", ...columnNames.map(each=>value[each]||0)])
}
await FileSystem.write({path:`${FileSystem.thisFolder}/terms.ignore.tsv`, data: csvOutput.map(each=>each.join(`\t`)).join("\n"), overwrite: true})
import { OperatingSystem } from "https://deno.land/x/quickr@0.8.0/main/operating_system.js"
import $ from "https://esm.sh/@jsr/david__dax@0.43.0/mod.ts"
const $$ = (...args)=>$(...args).noThrow()
// await $$`false`
// await $$`false`.text("stderr")
await $$`code ${FileSystem.thisFolder}/terms.ignore.tsv`
// OperatingSystem.openUrl(`file://${FileSystem.makeAbsolutePath(`${FileSystem.thisFolder}/terms.ignore.tsv`)}`)